Add Disable SSL and Force Path Style options.
ribbybibby/s3_exporter pull request #5
Opened 2019-07-02 15:23 UTC by maxpospelov

2019-07-18 09:17 UTC, ribbybibby requested changes
Can you please document these options in the README?

2019-07-18 09:17 UTC, ribbybibby commented on s3_exporter.go
> +		forcePathStyle = app.Flag("s3.force-path-style", "Custom force path style").Bool()
Can you align these `=` signs, please?

2019-07-18 12:21 UTC, maxpospelov commented on s3_exporter.go
> +		forcePathStyle = app.Flag("s3.force-path-style", "Custom force path style").Bool()
Done

2019-07-18 12:27 UTC, maxpospelov commented
> Can you please document these options in the README?

I documented these options in the  README.

2019-07-18 12:29 UTC, maxpospelov commented
@ribbybibby Can you check it please?

2019-08-15 16:48 UTC, ribbybibby approved these changes
Thanks @maxpospelov. Sorry for the long wait; it looks good to me.

2019-08-16 07:08 UTC, merged

2020-08-01 18:39 UTC, sarthak40 commented
@ribbybibby could you make a release & update dockerhub for this commit please?